services:
  minecraft:
    environment:
      MODRINTH_PROJECTS: ${FRIEND_PAPER_MODRINTH_PROJECTS:-treechopper}
      MAX_PLAYERS: ${FRIEND_MINECRAFT_MAX_PLAYERS:-8}
      MOTD: ${FRIEND_MINECRAFT_MOTD:-Craftalism Friends Server}
      DIFFICULTY: ${FRIEND_MINECRAFT_DIFFICULTY:-normal}
      MODE: ${FRIEND_MINECRAFT_MODE:-survival}
      VIEW_DISTANCE: ${FRIEND_MINECRAFT_VIEW_DISTANCE:-6}
      SIMULATION_DISTANCE: ${FRIEND_MINECRAFT_SIMULATION_DISTANCE:-4}
      ONLINE_MODE: ${FRIEND_MINECRAFT_ONLINE_MODE:-TRUE}
    ports:
      - "${FRIEND_MINECRAFT_PORT:-25565}:25565"
