#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-up}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_ROOT="${TEST_WORKSPACE_ROOT:-/tmp/craftalism-test-mode}"
ENV_FILE="${TEST_ENV_FILE:-${ROOT_DIR}/.test-mode.env}"

AUTH_SERVER_REPO_URL="${AUTH_SERVER_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-authorization-server.git}"
API_REPO_URL="${API_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-api.git}"
DASHBOARD_REPO_URL="${DASHBOARD_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-dashboard.git}"
ECONOMY_REPO_URL="${ECONOMY_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-economy.git}"

AUTH_SERVER_BRANCH="${AUTH_SERVER_BRANCH:-main}"
API_BRANCH="${API_BRANCH:-main}"
DASHBOARD_BRANCH="${DASHBOARD_BRANCH:-main}"
ECONOMY_BRANCH="${ECONOMY_BRANCH:-main}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command '$1' is not installed." >&2
    exit 1
  }
}

validate_repo_url() {
  local name="$1"
  local url="$2"
  if [[ -z "${url}" ]]; then
    echo "Error: ${name} is empty. Set ${name} to a valid Git URL." >&2
    exit 1
  fi
}

sync_repo() {
  local name="$1"
  local url="$2"
  local branch="$3"
  local target_dir="$4"

  echo "==> Syncing ${name} (${branch})"
  if [[ ! -d "${target_dir}/.git" ]]; then
    rm -rf "${target_dir}"
    git clone --branch "${branch}" --single-branch "${url}" "${target_dir}"
  else
    git -C "${target_dir}" remote set-url origin "${url}"
    git -C "${target_dir}" fetch --prune origin "${branch}"
    git -C "${target_dir}" checkout -B "${branch}" "origin/${branch}"
    git -C "${target_dir}" reset --hard "origin/${branch}"
    git -C "${target_dir}" clean -fd
  fi
}

build_economy_plugin() {
  local repo_dir="$1"
  local output_jar=""

  echo "==> Building economy plugin from ${repo_dir}"

  if [[ -x "${repo_dir}/gradlew" ]]; then
    docker run --rm -v "${repo_dir}:/workspace" -w /workspace gradle:8.7.0-jdk21 ./gradlew --no-daemon clean build -x test
    output_jar="$(find "${repo_dir}/build/libs" -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' ! -name '*-plain.jar' | head -n 1)"
  elif [[ -f "${repo_dir}/pom.xml" ]]; then
    docker run --rm -v "${repo_dir}:/workspace" -w /workspace maven:3.9.11-eclipse-temurin-21 mvn -DskipTests clean package
    output_jar="$(find "${repo_dir}/target" -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' | head -n 1)"
  else
    echo "Error: economy repo must contain either gradlew or pom.xml to build a plugin jar." >&2
    exit 1
  fi

  if [[ -z "${output_jar}" ]]; then
    echo "Error: failed to locate built economy plugin jar." >&2
    exit 1
  fi

  echo "${output_jar}"
}

compose_cmd() {
  docker compose --env-file "${ROOT_DIR}/.env" --env-file "${ENV_FILE}" -f "${ROOT_DIR}/docker-compose.yml" -f "${ROOT_DIR}/docker-compose.test.yml" "$@"
}

require_cmd git
require_cmd docker

mkdir -p "${WORKSPACE_ROOT}"

if [[ "${MODE}" == "down" ]]; then
  if [[ ! -f "${ENV_FILE}" ]]; then
    echo "No ${ENV_FILE} found; running down with base .env only."
    docker compose --env-file "${ROOT_DIR}/.env" -f "${ROOT_DIR}/docker-compose.yml" -f "${ROOT_DIR}/docker-compose.test.yml" down
  else
    compose_cmd down
  fi
  exit 0
fi

validate_repo_url AUTH_SERVER_REPO_URL "${AUTH_SERVER_REPO_URL}"
validate_repo_url API_REPO_URL "${API_REPO_URL}"
validate_repo_url DASHBOARD_REPO_URL "${DASHBOARD_REPO_URL}"
validate_repo_url ECONOMY_REPO_URL "${ECONOMY_REPO_URL}"

AUTH_SERVER_DIR="${WORKSPACE_ROOT}/auth-server"
API_DIR="${WORKSPACE_ROOT}/api"
DASHBOARD_DIR="${WORKSPACE_ROOT}/dashboard"
ECONOMY_DIR="${WORKSPACE_ROOT}/economy"

sync_repo "authorization server" "${AUTH_SERVER_REPO_URL}" "${AUTH_SERVER_BRANCH}" "${AUTH_SERVER_DIR}"
sync_repo "api" "${API_REPO_URL}" "${API_BRANCH}" "${API_DIR}"
sync_repo "dashboard" "${DASHBOARD_REPO_URL}" "${DASHBOARD_BRANCH}" "${DASHBOARD_DIR}"
sync_repo "economy plugin" "${ECONOMY_REPO_URL}" "${ECONOMY_BRANCH}" "${ECONOMY_DIR}"

ECONOMY_PLUGIN_JAR_PATH="$(build_economy_plugin "${ECONOMY_DIR}")"

cat > "${ENV_FILE}" <<EOV
# Auto-generated by scripts/test-mode.sh
AUTH_SERVER_SRC_DIR=${AUTH_SERVER_DIR}
API_SRC_DIR=${API_DIR}
DASHBOARD_SRC_DIR=${DASHBOARD_DIR}
ECONOMY_PLUGIN_JAR_PATH=${ECONOMY_PLUGIN_JAR_PATH}
EOV

echo "==> Starting test stack with automatic rebuild"
compose_cmd up -d --build --remove-orphans
