#!/usr/bin/env bash
set -euo pipefail

MODE="${1:-up}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKSPACE_ROOT="${TEST_WORKSPACE_ROOT:-/tmp/craftalism-test-mode}"
REPOS_ROOT="${WORKSPACE_ROOT}/repos"
ARTIFACTS_ROOT="${WORKSPACE_ROOT}/artifacts"
ENV_FILE="${TEST_ENV_FILE:-${ROOT_DIR}/.test-mode.env}"

AUTH_SERVER_REPO_URL="${AUTH_SERVER_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-authorization-server.git}"
API_REPO_URL="${API_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-api.git}"
DASHBOARD_REPO_URL="${DASHBOARD_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-dashboard.git}"
ECONOMY_REPO_URL="${ECONOMY_REPO_URL:-https://github.com/HenriqueMichelini/craftalism-economy.git}"

AUTH_SERVER_BRANCH="${AUTH_SERVER_BRANCH:-main}"
API_BRANCH="${API_BRANCH:-main}"
DASHBOARD_BRANCH="${DASHBOARD_BRANCH:-main}"
ECONOMY_BRANCH="${ECONOMY_BRANCH:-main}"

AUTH_SERVER_REPO_DIR="${REPOS_ROOT}/craftalism-authorization-server"
API_REPO_DIR="${REPOS_ROOT}/craftalism-api"
DASHBOARD_REPO_DIR="${REPOS_ROOT}/craftalism-dashboard"
ECONOMY_REPO_DIR="${REPOS_ROOT}/craftalism-economy"

# Explicit deterministic build mapping (no heuristics):
# - auth-server -> java/
# - api         -> java/
# - dashboard   -> react/
# - economy     -> java/ (plugin build only)
AUTH_SERVER_BUILD_CONTEXT="${AUTH_SERVER_REPO_DIR}/java"
AUTH_SERVER_DOCKERFILE="dockerfile"
API_BUILD_CONTEXT="${API_REPO_DIR}/java"
API_DOCKERFILE="dockerfile"
DASHBOARD_BUILD_CONTEXT="${DASHBOARD_REPO_DIR}/react"
DASHBOARD_DOCKERFILE="dockerfile"
ECONOMY_PLUGIN_PROJECT_DIR="${ECONOMY_REPO_DIR}/java"
ECONOMY_PLUGIN_OUTPUT_JAR="${ARTIFACTS_ROOT}/craftalism-economy.jar"

log() {
  echo "[test-mode] $*"
}

fail() {
  echo "[test-mode] ERROR: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "required command '$1' is not installed"
}

validate_repo_url() {
  local name="$1"
  local url="$2"
  [[ -n "${url}" ]] || fail "${name} is empty; set it to a valid Git URL"
}

sync_repo() {
  local service_name="$1"
  local repo_url="$2"
  local branch="$3"
  local repo_dir="$4"

  log "Syncing ${service_name} repository"
  log "  repo:   ${repo_url}"
  log "  branch: ${branch}"
  log "  path:   ${repo_dir}"

  if [[ ! -d "${repo_dir}/.git" ]]; then
    mkdir -p "$(dirname "${repo_dir}")"
    git clone --branch "${branch}" --single-branch "${repo_url}" "${repo_dir}" \
      || fail "failed to clone ${service_name} repository"
    return
  fi

  git -C "${repo_dir}" remote set-url origin "${repo_url}" \
    || fail "failed to set origin URL for ${service_name}"

  if ! git -C "${repo_dir}" pull --ff-only origin "${branch}"; then
    fail "failed to pull ${service_name} (${branch}). Resolve local conflicts/divergence in ${repo_dir}, then re-run."
  fi
}

validate_path() {
  local label="$1"
  local path="$2"
  [[ -e "${path}" ]] || fail "${label} not found: ${path}"
}

build_economy_plugin() {
  local project_dir="$1"
  local output_jar="$2"
  local built_jar=""

  log "Building economy plugin"
  log "  project dir: ${project_dir}"

  mkdir -p "$(dirname "${output_jar}")"

  if [[ -f "${project_dir}/gradlew" ]]; then
    chmod +x "${project_dir}/gradlew" || true
    docker run --rm -v "${project_dir}:/workspace" -w /workspace gradle:8.7.0-jdk21 sh ./gradlew --no-daemon clean build -x test \
      || fail "economy plugin Gradle build failed"

    built_jar="$(find "${project_dir}/build/libs" -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' ! -name '*-plain.jar' | head -n 1 || true)"
  elif [[ -f "${project_dir}/pom.xml" ]]; then
    docker run --rm -v "${project_dir}:/workspace" -w /workspace maven:3.9.11-eclipse-temurin-21 mvn -DskipTests clean package \
      || fail "economy plugin Maven build failed"

    built_jar="$(find "${project_dir}/target" -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar' | head -n 1 || true)"
  else
    fail "economy plugin project must contain either ${project_dir}/gradlew or ${project_dir}/pom.xml"
  fi

  [[ -n "${built_jar}" ]] || fail "could not locate built plugin JAR in ${project_dir}"

  cp -f "${built_jar}" "${output_jar}" || fail "failed to copy plugin JAR to ${output_jar}"
  log "  plugin jar: ${output_jar}"
}

write_test_env() {
  log "Writing test-mode env file: ${ENV_FILE}"
  cat > "${ENV_FILE}" <<EOT
# Auto-generated by scripts/test-mode.sh
# Test mode only. Production env files are untouched.
AUTH_SERVER_BUILD_CONTEXT=${AUTH_SERVER_BUILD_CONTEXT}
AUTH_SERVER_DOCKERFILE=${AUTH_SERVER_DOCKERFILE}
API_BUILD_CONTEXT=${API_BUILD_CONTEXT}
API_DOCKERFILE=${API_DOCKERFILE}
DASHBOARD_BUILD_CONTEXT=${DASHBOARD_BUILD_CONTEXT}
DASHBOARD_DOCKERFILE=${DASHBOARD_DOCKERFILE}
ECONOMY_PLUGIN_JAR_PATH=${ECONOMY_PLUGIN_OUTPUT_JAR}
EOT
}

compose_cmd() {
  docker compose \
    --env-file "${ROOT_DIR}/.env" \
    --env-file "${ENV_FILE}" \
    -f "${ROOT_DIR}/docker-compose.yml" \
    -f "${ROOT_DIR}/docker-compose.test.yml" "$@"
}

require_cmd git
require_cmd docker

mkdir -p "${REPOS_ROOT}" "${ARTIFACTS_ROOT}"

if [[ "${MODE}" == "down" ]]; then
  log "Stopping test-mode stack"
  if [[ ! -f "${ENV_FILE}" ]]; then
    fail "${ENV_FILE} does not exist. Run test mode 'up' first, or set TEST_ENV_FILE to a valid file."
  fi
  compose_cmd down
  exit 0
fi

log "Starting test-mode orchestration"

validate_repo_url AUTH_SERVER_REPO_URL "${AUTH_SERVER_REPO_URL}"
validate_repo_url API_REPO_URL "${API_REPO_URL}"
validate_repo_url DASHBOARD_REPO_URL "${DASHBOARD_REPO_URL}"
validate_repo_url ECONOMY_REPO_URL "${ECONOMY_REPO_URL}"

# 1) Sync repos
sync_repo "auth-server" "${AUTH_SERVER_REPO_URL}" "${AUTH_SERVER_BRANCH}" "${AUTH_SERVER_REPO_DIR}"
sync_repo "api" "${API_REPO_URL}" "${API_BRANCH}" "${API_REPO_DIR}"
sync_repo "dashboard" "${DASHBOARD_REPO_URL}" "${DASHBOARD_BRANCH}" "${DASHBOARD_REPO_DIR}"
sync_repo "economy" "${ECONOMY_REPO_URL}" "${ECONOMY_BRANCH}" "${ECONOMY_REPO_DIR}"

# 2) Validate expected directories/files from explicit mapping
validate_path "auth-server build context" "${AUTH_SERVER_BUILD_CONTEXT}"
validate_path "auth-server dockerfile" "${AUTH_SERVER_BUILD_CONTEXT}/${AUTH_SERVER_DOCKERFILE}"
validate_path "api build context" "${API_BUILD_CONTEXT}"
validate_path "api dockerfile" "${API_BUILD_CONTEXT}/${API_DOCKERFILE}"
validate_path "dashboard build context" "${DASHBOARD_BUILD_CONTEXT}"
validate_path "dashboard dockerfile" "${DASHBOARD_BUILD_CONTEXT}/${DASHBOARD_DOCKERFILE}"
validate_path "economy plugin project" "${ECONOMY_PLUGIN_PROJECT_DIR}"

# 3) Build plugin
build_economy_plugin "${ECONOMY_PLUGIN_PROJECT_DIR}" "${ECONOMY_PLUGIN_OUTPUT_JAR}"

# 4) Generate dedicated test env and run compose
write_test_env

log "Launching docker compose (base + test override)"
compose_cmd up --build -d

log "Test mode is up"
